[project]
name = "photo-anlyzer"
version = "0.1.0"
description = "Service to analyze photos"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "aiohttp>=3.11.18",
    "alembic>=1.15.2",
    "asyncpg>=0.30.0",
    "facenet-pytorch>=2.5.3",
    "nltk>=3.9.1",
    "numpy>=2.2.5",
    "pillow>=11.2.1",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
    "sqlalchemy[asyncio]>=2.0.40",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
