"""reccomendation_api

Revision ID: 6b2b4297acec
Revises: 1783cb09ba49
Create Date: 2025-05-15 20:37:05.033410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
import pgvector

# revision identifiers, used by Alembic.
revision: str = '6b2b4297acec'
down_revision: Union[str, None] = '1783cb09ba49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "postgis"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='GEOGRAPHY', nullable=False), nullable=False),
    sa.Column('geo_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('tags', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_column('descriptions', 'tags')
    op.add_column('descriptions', 
                  column=sa.Column(
                      'tags', 
                      type_=pgvector.sqlalchemy.vector.VECTOR(dim=512), 
                      nullable=False
                  ))


    op.alter_column('descriptions', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=False)

    op.add_column('photos', sa.Column('photo', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False))
    op.drop_column('photos', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('photos', 'photo')
    op.alter_column('descriptions', 'tags',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_table('users')
    op.drop_table('preferences')
    op.drop_table('geo')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS "postgis"')
