name: Push to main branch workflow

on:
  push:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          for service in 'photo' 'swipe' 'text' 'user' 'migration'; do
          docker build -t ghcr.io/${{ github.repository }}-$service:${{ env.BUILD_DATE }}-${{ github.sha }} \
          -f docker/$service.Dockerfile .
          done
      - name: Push Docker image
        run: |
          for service in 'photo' 'swipe' 'text' 'user' 'migration'; do
          docker push ghcr.io/${{ github.repository }}-$service:${{ env.BUILD_DATE }}-${{ github.sha }}
          done
